name: wits_overflow
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  fluttertoast: ^8.0.6
  flutter:
    sdk: flutter
  material_floating_search_bar: ^0.3.4  
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2

  # google and firebase
  firebase_core: ^1.1.0
  firebase_auth: ^1.1.2
  firebase_analytics: ^5.0.2
  cloud_firestore: ^2.0.0
  google_sign_in: ^5.0.2

  # Local storage
  flutter_secure_storage: ^4.2.0
  universal_html: ^2.0.8

  # Api requests
  http: ^0.13.2

  # Environmental Variables
  flutter_dotenv: ^4.0.0-nullsafety.0


  meta: ^1.3.0
  provider: ^5.0.0-nullsafety.3

dev_dependencies:
  flutter_test:
    sdk: flutter



# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
    #- assets/images/wits_logo_transparent.png
    #- assets/images/google_logo.png
  assets:
    - assets/images/
    - env/.env_dev
    - env/.env_pre
    - env/.env_prod

